### PR TITLE
Merging kafka-connect-hdfs 3.3.0 to support Kafka 0.11

### PR DESCRIPTION
**Pull request by lewisdawson**
This allows the connector to work with Kafka 0.11. I also upgraded Guava to 20.0 to fix the `NoSuchMethodError` I was seeing under #48.

### CODE REVIEW

File: Jenkinsfile [hunk 1]
```diff
@@ -0,0 +1,4 @@
+#!/usr/bin/env groovy
+common {
+  slackChannel = '#connect-eng'
+}
```
Comment (OneCricketeer) [inline Jenkinsfile:4]: Is the Jenkinsfile needed?

**Comment by PraveenSeluka** [comment]
Hi @lewisdawson thanks for your work on this. Will love to discuss how we can test this and get it merged. Are you open for a chat ? (My email is praveen.seluka@gmail.com)

**Comment by OneCricketeer** [comment]
@lewisdawson Any plans to upgrade this PR to 4.0? 

HDFS connect was refactored to use [kafka-connect-storage-common](https://github.com/confluentinc/kafka-connect-storage-common)
